### ISSUE TITLE
中文输入法下输入英文字母，光标会移动到输入框内容中间

### ISSUE THREAD

**Issue by seemrcola** [webfansplz/vtui-npm#2]
中文输入法下输入英文字母，光标会移动到输入框内容中间，导致无法删除后面的内容。
- 英文输入下不会有这个问题。
- 中文输入法只输入两个以下文字正常，两个以上会导致光标停留在第二个文字。
- 中文输入法下输入英文会导致光标位置异常，同样是停留在第二个字母。

**Comment by seemrcola** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/110106669/200458374-832b1c3e-7b89-4b79-9354-5945a2ed4c25.png">

**Comment by webfansplz** [comment]
Fixed in v0.0.1-beta.16
