### ISSUE TITLE
win使用命令后报错

### ISSUE THREAD

**Issue by scripted-C20** [webfansplz/vtui-npm#3]
win安装（不管是全局还是局部）后使用命令出现可视化，随意输入后报错

![965a52b7cc0df75be4e79224f08891c](https://user-images.githubusercontent.com/36700965/200456984-b7492a7d-d0c3-45d2-b7d5-8c28c8ea4f71.png)

![8d83295412f6b182fd144c90bda51fc](https://user-images.githubusercontent.com/36700965/200457043-af10a7b1-df8b-4afa-8c83-46648849a881.png)

**Comment by webfansplz** [comment]
可以升级到`0.0.1-beta.20`再截图报错信息看看

**Comment by scripted-C20** [comment]
输入没问题了，现在是host出了问题（墙外墙内都不会出现）
![image](https://user-images.githubusercontent.com/36700965/200499302-56dd3fb0-2565-4657-bbb4-49f7a18cf9db.png)

**Comment by webfansplz** [comment]
这个报错应该是被搜索API block了, 可以关注下这个 [#4 ](https://github.com/webfansplz/vtui-npm/issues/4) 到时候会支持切换别的源.

**Comment by webfansplz** [comment]
> 这个报错应该是被搜索API block了, 可以关注下这个 [#4 ](https://github.com/webfansplz/vtui-npm/issues/4) 到时候会支持切换别的源.

最新版本已支持,可以试试看
