### ISSUE TITLE
是否考虑换一个搜索接口

### ISSUE THREAD

**Issue by Soya-xy** [webfansplz/vtui-npm#4]
利用`npm search` 或者 `http://registry.npmjs.com/-/v1/search?text=` 进行搜索

避免`algolia`带来未知/网络报错

**Comment by webfansplz** [comment]
IMO, `Algolia` search is actually a good solution. But I think we can have some options for ppl to choose from. i.e.

```shell
vnpm --registry=xxx # algolia by default
```
