### ISSUE TITLE
安装完之后 vnpm 

### ISSUE THREAD

**Issue by king-open** [webfansplz/vtui-npm#9]
直接报错 没有 vnpm 

我是用 `pnpm i vtui-npm` 装的 打开不了 

![截屏2022-11-10 00.13.16.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/f083e5ebb21448afb437d1de30be61fd~tplv-k3u1fbpfcp-watermark.image?)

**Comment by webfansplz** [comment]
不是全局安装的话，需要npx vnpm. (如果还有问题,再重新打开Issue)
